version: '3.8'

services:
  # Nginx Reverse Proxy - Main entry point
  nginx:
    image: ${CONTAINER_REGISTRY}/${IMAGE_REPOSITORY}-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

  # Backend API Service
  backend:
    image: ${CONTAINER_REGISTRY}/${IMAGE_REPOSITORY}-backend:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}
      - REDIS_AUTH_MODE=${REDIS_AUTH_MODE}
    networks:
      - app-network
    restart: always

  # React Frontend Service  
  frontend:
    image: ${CONTAINER_REGISTRY}/${IMAGE_REPOSITORY}-frontend:${IMAGE_TAG}
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
