version: '3.8'

# Development overrides for The Cycle
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
      args:
        SERVICE: backend
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "8080:8080"
    volumes:
      - ./src/express-backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        SERVICE: frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3001:3001"
    volumes:
      - ./src/web-frontend:/app/src
      - /app/node_modules
      - /app/build
    command: npm start
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
